# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4

# Mod Properties
mod_version=1.2.3
maven_group=us.potatoboy
archives_base_name=htm

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.144.0+26.1
translation_version=3.0.1+26.1
permissions_api_version=0.7.0
protection_api_version=2.0.0
